#!/usr/bin/env bash
# Render nginx geo block for campus/IP auth bypass from INSTITUTIONAL_CIDRS.
# Example: INSTITUTIONAL_CIDRS="10.0.0.0/8,192.168.0.0/16,169.58.217.0/24"
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck disable=SC1091
[[ -f "$ROOT/.env" ]] && source "$ROOT/.env"

OUT="$ROOT/nginx/campus-ip.geo.conf"
CIDRS="${INSTITUTIONAL_CIDRS:-}"

{
  echo "# AUTO-GENERATED by scripts/render-campus-geo.sh"
  echo "geo \$campus_ip {"
  echo "    default 0;"
  if [[ -n "$CIDRS" ]]; then
    IFS=',' read -ra parts <<< "$CIDRS"
    for cidr in "${parts[@]}"; do
      cidr_trimmed="$(echo "$cidr" | xargs)"
      [[ -n "$cidr_trimmed" ]] || continue
      echo "    ${cidr_trimmed} 1;"
    done
  fi
  echo "}"
} > "$OUT"

echo "Wrote $OUT"
cat "$OUT"
